### ISSUE TITLE
Fatal Error Installing

### ISSUE THREAD

**Issue by mashdun** [jawittdesigns/bbpress-live-preview#1]
When trying to install, I get a fatal error.

Parse error: syntax error, unexpected 'include' (T_INCLUDE), expecting identifier (T_STRING) in /home/ott/public_html/wp-content/plugins/bbpress-live-preview-master/helpers/class-file-include.php on line 91 

Looks like a syntax error, but I'd not good with PHP, so not sure what the issue is

**Comment by jawittdesigns** [comment]
Yeah, I've had this issue before. I just pushed a new version. See if this clears up the fatal error.

**Comment by mashdun** [comment]
Thanks, but I'm not seeing the update.

**Comment by jawittdesigns** [comment]
Sorry about that, It's there now.
