### ISSUE TITLE
CSS and JS files aren't in repository?

### ISSUE THREAD

**Issue by NickOrtiz** [jawittdesigns/bbpress-live-preview#2]
I see a handful of includes that are returning a 404 error for me.  

including: 
- includes/assets/js/scripts.min.js
- includes/assets/css/styles.css
- admin/assets/js/scripts.min.js
- admin/assets/css/styles.css

Did I somehow grab an incomplete copy of the plugin? --or are these files not actually added to the repo for some reason?

**Comment by jawittdesigns** [comment]
Hey @NickOrtiz, seems like they got knocked off my last build.

Everything should be there now.

**Comment by NickOrtiz** [comment]
Awesome, no more 404's and the color picker works now!  --the preview pane still isn't working for me, but that's probably best addressed in a separate ticket.
